name: Sample github workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: print the files which are checkout
        run: ls
      - name: Setup java
        uses: actions/setup-java@v5.0.0
        with:
          java-version: 17
          distribution: microsoft
      - name: Building the code
        run: |
          mvn --batch-mode --update-snapshots verify   # it will generate target folder and jar
          ls
        
        
      
        
  
